### ISSUE TITLE
What is this SyndFeed and SyndEnclosure? and where are they imported here? 

### ISSUE THREAD

**Issue by MehdiHali** [ucuf/podapter#24]
https://github.com/usephel/podapter/blob/357b230480cfc67c46833a0832d9dfc2d2d569fd/podcastService/src/main/java/main/services/PodcastService.java#L19

**Comment by elevennprime** [comment]
There are imported here
https://github.com/usephel/podapter/blob/357b230480cfc67c46833a0832d9dfc2d2d569fd/podcastService/src/main/java/main/services/PodcastService.java#L3
The SyndFeed class, which is part of the Rome library, is used for generating the XML feed.
